# Site settings
title: HYOLAB
description: 'Front page'
url: 'http://soyhyoj.github.io'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bg.jpg'
google_analytics: UA-178278212-1
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'soyhyoj'
  email: soyhyoj@gmail.com
  twitter_username: _soyhyoj
  github_username:  soyhyoj
  linkedin_username:  soyhyoj

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
